using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using ET_Project_GUI.Network;
using ET_Project_GUI.ET_Calibration;
using System.IO;
using System.Diagnostics;
using System.Drawing.Imaging;
using System.Threading;
using ET_Project_GUI.Testing;

namespace ET_Project_GUI
{
    public partial class MainForm : Form
    {
        //global variables
        private ETController ETDevice;
        private ETCalibrate calibrateET;
        private CustomScreenCapture screenVideo;
        private bool updatePoints;

        /// <summary>
        /// This is the main form that we will use in a windows based environment. It also sets the default selections for the dropdown/combo boxes
        /// </summary>
        public MainForm()
        {       
                      
            //init components
            ETDevice = new ETController();
            calibrateET = new ETCalibrate();
            screenVideo = new CustomScreenCapture();
            updatePoints = true;

            //init ui components (auto generated)
            InitializeComponent();

            //setup the default combobox selections
            callibrationPointComboBox.SelectedIndex = 2;
            targetShapeComboBox.SelectedIndex = 0;
            dataSampleRateComboBox.SelectedIndex = 2;

            //start the ET positition data updater
            //TODO "SHANE" update to use real ET data (not generated)
            Thread etPoisitionUpdater = new Thread(new ThreadStart(updatePointGenerator));
            etPoisitionUpdater.Name = "TESTING - random eye position generator Thread";
            etPoisitionUpdater.Start();
        }
        private void onProgramClose()
        {
            //stop recoding the avi video on close (prevents corruption of avi file)
            this.screenVideo.stopRecording();

            //kill the update point thread
            updatePoints = false;

        }
        private void MainForm_Load(object sender, EventArgs e)
        {

        }
        //*******************************************
        //      CALIBRATION
        //*******************************************
        /// <summary>
        /// This is the button click handler used to load and connect the application to the eye tracking server
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void Cal_Connect_Button_Click(object sender, EventArgs e)
        {

            // TODO "Future release" launch SMI Eye tracker server automatically

            //disable the remote view button as this will be dedicated as a "subject computer"
            Obs_RemoteView_Button.Enabled = false;

            ETConnection connectToEyeTracker = new ETConnection();
            int res =  connectToEyeTracker.connect(ETDevice);


            if (res == 104)//res 104 is used if no server has been started
            {
                DialogResult messagebox = MessageBox.Show("Could not connect to SMI Eye Tracker\n\nPlease check the Eye Tracker server has been started", "Error Connecting to Eye Tracker Server",
                    MessageBoxButtons.RetryCancel, MessageBoxIcon.Error);
                if (messagebox == DialogResult.Retry)
                {
                    Cal_Connect_Button_Click(sender, e);
                }
                
            }
            else if (res != 1)//any other message (see SMI manual for error codes)
            {
                //display message box
                MessageBox.Show("Could not connect to Eye Tracker!", "Error Connecting to Eye Tracker Server",
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            else//connection succesful enable next step
            {
                //Display eye position on the observation monitor
                ETTrackingMonitor trackingMonitor = new ETTrackingMonitor(ETDevice, observationMonitorPictureBox);
               
                //enable trackingmonitor and eyeimage monitor button (code should auto load this view first time)
                Obs_TrackingMonitor_Button.Enabled = true;
                Obs_EyeImageMonitor_Button.Enabled = true;
                
                //Allow/Enable the next step (Calibration)
                Cal_Calibrate_Button.Enabled = true;
            }
        }
        /// <summary>
        /// This  is the button click handler used to calibrate the eye tracker
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void Cal_Calibrate_Button_Click(object sender, EventArgs e)
        {
            if(calibrateET.Calibrate(ETDevice) != 1)
            {
                DialogResult messagebox = MessageBox.Show("Calibration for the Eye Tracker failed", "Error Calibrating Eye Tracker",
                MessageBoxButtons.RetryCancel, MessageBoxIcon.Error);
                if (messagebox == DialogResult.Retry)
                {
                    Cal_Calibrate_Button_Click(sender, e);
                }
            }
            else
            { 
                Cal_Validate_Button.Enabled = true;
            }
        }
        /// <summary>
        /// This  is the button click handler used to validate the eye tracker calibration
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void Cal_Validate_Button_Click(object sender, EventArgs e)
        {
            ETValidate etVal = new ETValidate();
            int result = etVal.validate(ETDevice, calibrationAccuracyPictureBox);
            
            if (result != 1)
            {
                DialogResult messagebox = MessageBox.Show("Validation for the Eye Tracker failed, Error #: "+result, "Error Validating Eye Tracker",
                MessageBoxButtons.RetryCancel, MessageBoxIcon.Error);
                if (messagebox == DialogResult.Retry)
                {
                    Cal_Validate_Button_Click(sender, e);
                }
            }
            else
            {
                //TODO "SHANE" Validate succesful logic
            }
        }
        /// <summary>
        /// This  is the button click handler that loads a larger view of the accuracy image
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void Cal_CheckAccuracy_Button_Click(object sender, EventArgs e)
        {
            // TODO "SHANE" add logic to check accuracy/load accuracy image ET
        }
        
//*******************************************
//      DATA RECORDING
//*******************************************
        /// <summary>
        /// This  is the button click handler used save the accuracy image to a jpg file for later reference
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void DataRec_SaveCalAcc_Button_Click(object sender, EventArgs e)
        {
            // TODO "SHANE" add save the calibration image
        }
        /// <summary>
        /// This  is the button click handler used to start recording eye tracker data (eye position) at a selected sample rate to out built in database. It also
        /// start the recording of the avi video with the eyeposition overlayed onto it
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void DataRec_StartDataRec_Button_Click(object sender, EventArgs e)
        {
            //AVI video recording thread
            try
            {
                Thread aviThread = new Thread(new ThreadStart(screenVideo.CaptureVideo));
                aviThread.Name = "AVI Recording Thread";
                aviThread.Start();

                
            }
            catch(Exception ex)
            {
                Console.WriteLine("Could not start video recording thread: "+ex);
            }


        }
        /// <summary>
        /// This  is the button click handler used to stop recording data and the AVI video
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void DataRec_StopDataRec_Button_Click(object sender, EventArgs e)
        {
            screenVideo.stopRecording();
        }
       
        //*******************************************
        //      OBSERVATION
        //*******************************************
        /// <summary>
        /// This  is the button click handler used to load the eye position monitor (show your eyes are in correct position). It is only enabled after your have succesfully connected to the ET.
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void Obs_TrackingMonitor_Button_Click(object sender, EventArgs e)
        {
            // TODO "SHANE" disable until connected to the ET server 

            // TODO "SHANE" add logic to load tracking monitor (the "white eyes" image)
        }
        /// <summary>
        /// This  is the button click handler used to load a live black and white video of your eyes
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void Obs_EyeImageMonitor_Button_Click(object sender, EventArgs e)
        {
            // TODO "SHANE" add logic to load Eye image monitor (the live black and white vid of your eyes)
        }
        /// <summary>
        /// This  is the button click handler used to load the remote view. Note that this option will become disabled if you are connected to the eye tracker. The purpose
        /// of this functionality is to watch someone on another comuter to observe what they are looking at in live time.
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void Obs_RemoteView_Button_Click(object sender, EventArgs e)
        {
            //disable all calibration buttons as this will be the "experimenters computer"
            Cal_Connect_Button.Enabled = false;
            Cal_Calibrate_Button.Enabled = false;
            Cal_Validate_Button.Enabled = false;
            Cal_CheckAccuracy_Button.Enabled = false;

            // TODO "SHANE" add logic for loading remote view
        }
        
//*******************************************
//      APPLICATIONS
//*******************************************
        /// <summary>
        /// This  is the button click handler used to load the Simon Says game
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void App_SimonSays_Button_Click(object sender, EventArgs e)
        {
            // TODO "SHANE/MATT" add logic for loading simon says app
        }
        /// <summary>
        /// This  is the button click handler used to load the Maze game
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void App_Maze_Button_Click(object sender, EventArgs e)
        {
            // TODO "SHANE/MATT" add logic for loading maze app
        }
        /// <summary>
        /// This  is the button click handler used to load the Keyboard control app
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void App_KeyboardControl_Button_Click(object sender, EventArgs e)
        {
            // TODO "PETER" add logic for loading keyboard control app
        }
        /// <summary>
        /// This  is the button click handler used to load the Mouse control app
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void App_MouseControl_Button_Click(object sender, EventArgs e)
        {
            // TODO "PETER/JOSH" add logic for loading mouse control app
        }
        /// <summary>
        /// This  is the button click handler used to load/launch any .exe file
        /// </summary>
        /// <param name="sender">Auto generated by the button</param>
        /// <param name="e">Auto generated by the button</param>
        private void App_OtherApps_Button_Click(object sender, EventArgs e)
        {
            OpenFileDialog openFileDialog = new OpenFileDialog();
            
            openFileDialog.Filter = "Executables|*.exe|All Files (*.*)|*.*";
            openFileDialog.FilterIndex = 1;
            DialogResult res = openFileDialog.ShowDialog();

            if (File.Exists(openFileDialog.FileName) && res == DialogResult.OK)
            {
                Process launcher = new Process();
                launcher.StartInfo.FileName = openFileDialog.FileName.ToString();
                launcher.Start();
            }
            else if (res == DialogResult.Cancel)
            {
            }
            else
            {
                MessageBox.Show("Error opening file!"); //Error message if the file does not open
            }
        }
//*******************************************
//      Testing area
//*******************************************
        private void callibrationDataChanged(object sender, EventArgs e)
        {
            //int ret = 0;
            int [] calibrationPoints = {1,2,5,9};
            int displayDevice = 0;
            int targetSize = 20;

            ETController.CalibrationStruct calData;
            calData.displayDevice = displayDevice;
            calData.autoAccept = 1;
            calData.method = calibrationPoints[callibrationPointComboBox.SelectedIndex];
            calData.visualization = 1;
            calData.speed = 0;
            calData.targetShape = targetShapeComboBox.SelectedIndex+2;
            calData.backgroundColor = 50;
            calData.foregroundColor = 250;
            calData.targetSize = targetSize;
            calData.targetFilename = "";

            calibrateET.SetupData = calData;
        }
        
        private void updateETEyePosition(Point newPosition)
        {
            //TODO "SHANE" add a call to update eye position when needed
            screenVideo.CurrentEyePosition = newPosition;
        }
        //TODO "SHANE" remove point generator before release
        public void updatePointGenerator()
        {
            RandomPointGenerator randPoint = new RandomPointGenerator();
            int ScreenWidth = Screen.PrimaryScreen.Bounds.Width;
            int ScreenHeight = Screen.PrimaryScreen.Bounds.Height;
            Point currentPoint;
            //TODO "SHANE" remove dependencies

            while(updatePoints)
            {
                currentPoint = randPoint.getPoint(ScreenWidth, ScreenHeight);
                updateETEyePosition(currentPoint);
                Thread.Sleep(100);
            }
        }

    }
}
